users = [
  {
    first_name: "brian",
    last_name: "welch",
    email: "myself@brianwelch.se",
    password: "12345678",
    user_name: "B-Dubs",
    birthday: "10-12-1974",
    street_address: "Vimpelgatan 17 lgh. 103",
    city: "malmö",
    county: "skåne",
    state: "",
    post_code: "21114",
    country: "Sweden",
    facebook_username: "",
    instagram_username: "",
    pinterest_username: "",
    children: false,
    time_preference: 60,
  }, {
    first_name: "beltrán",
    last_name: "sainz de vicuña nowack",
    email: "gorthor@gmail.com",
    password: "12345678",
    user_name: "",
    birthday: "",
    street_address: "",
    city: "",
    county: "",
    state: "",
    post_code: "",
    country: "",
    facebook_username: "",
    instagram_username: "",
    pinterest_username: "",
    children: false,
    time_preference: 60,
  }, {
    first_name: "makena",
    last_name: "hawley",
    email: "makena.hawley@gmail.com",
    password: "12345678",
    user_name: "",
    birthday: "",
    street_address: "",
    city: "",
    county: "",
    state: "",
    post_code: "",
    country: "",
    facebook_username: "",
    instagram_username: "",
    pinterest_username: "",
    children: false,
    time_preference: 60,
  }
]

food_preferences = %w[vegetarian vegan pork beef chicken fish shell-fish]
food_allergies = %w[peanut lactose gluten shell-fish]
special_diets = %w[atkins raw weight-watchers zone]
